### ISSUE TITLE
Error thrown on multiselectpicklist cmp when typing in search string

### ISSUE THREAD

**Issue by matejp84** [appiphony/Strike-Components#22] opened 2017-05-17 07:13 UTC
This is what I get when I try to type any text in input to search:

This page has an error. You might just need to refresh it. Access Check Failed! AttributeSet.get(): attribute 'focusIndex' of component 'markup://aura:iteration {96:111;a}' is not visible to 'markup://c:strike_multiSelectPicklist {95:111;a} {dealerPick}'. Failing descriptor: {markup://c:strike_multiSelectPicklist}

Error is thrown on VF page that has inside LEX component that is containing all other components. If I turn on LEX and open sam component browser just hangs and whole computer come to crawl - memory usage goes up by 200% and more. So currently this component has a very serious bug and I need this to work on production asap, if you can look into it?

**Comment by kevinberonilla** [comment] 2017-05-17 12:33
Hi @matejp84, do you know what version of `strike_multiSelectPicklist` you are using?

Also, you mentioned you're using this in a VF page (with Lightning Out). Do you know this is also happening for you inside LEX, like in a standard record or Lightning flexipage?

**Comment by trentchilders** [comment] 2017-05-17 13:40
Hi @matejp84, I haven't been able to reproduce your error. Any chance you can share your code on how you have this implemented?

**Comment by matejp84** [comment] 2017-05-17 17:03
I'm using one strike-select and 5 multiselect_picklists components, the rest of the code is mine/custom.

As I wrote: the same happens even when using component directly inside LEX. It is even worse as whole computer comes to crawl and RAM just gets filled up (on windows machine up to 81% of 16GB eaten just by one tab in chrome). 

as for code, here are few snippets out of my code:
this is how component is residing inside html:
`<div class="slds-form-element">
                            <c:strike_multiSelectPicklist value="" label="Dealers:" placeholder="Dealers" aura:id="dealerPick" >
                                <aura:iteration items="{!v.dealers}" var="option">
                                    <c:strike_option label="{!option.Name}" value="{!option.Id}"/>
                                </aura:iteration>
                            </c:strike_multiSelectPicklist>
                        </div>`

Here I have event:
`<aura:handler name="onchange" event="c:strike_evt" action="{!c.picklistChanged}"/>`

and here is function behind, that doesn't get called at all on production, but on sandbox it works OK with just some errors.
`picklistChanged: function (cmp, event, helper) {
        console.log(event.source.get("v.value"));

        let source = event.source.getLocalId();
        let value = event.source.get("v.value");
if(source == "dealerPick"){ 
//dosomething... in major just calls to backend to fetch new data...
}
}`

On production component (page) isn't working at all, but on sandbox I get fired this function at least. 
Here is error I get on production:
This page has an error. You might just need to refresh it. Action failed: c:DORCmp$controller$picklistChanged [Cannot read property 'get' of undefined] Failing descriptor: {c:DORCmp$controller$picklistChanged}

**Comment by trentchilders** [comment] 2017-05-18 20:16
Thanks for identifying this bug. We will be sure to have it fixed in a later release. For now, as a work around, you can try dynamically creating your `strike_option` components in the controller using `$A.createComponent` as is detailed in the documentation here. 

https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/js_cb_dynamic_cmp_async.htm

Then set an array of your newly created components into the `v.body` of your `strike_multiselectPicklist` component.

It seems to be the `aura:iteration` that is messing it up.

**Comment by matejp84** [comment] 2017-05-19 10:44
I can confirm, that this workaround works, but still have problems where I have default values set before data is retrieved from database. Works on both sandbox and production instances.

**Comment by trentchilders** [comment] 2017-05-19 13:35
Are you setting the default value of your `strike_multiSelectPicklist` as semicolon separated values in a string?

**Comment by matejp84** [comment] 2017-05-22 07:01
Default value is empty string.

**Comment by trentchilders** [comment] 2017-05-22 17:03
I guess I'm not sure what the issue is then. You said that you are having problems where you have default values set before data is retrieved from database. What is happening?

**Comment by matejp84** [comment] 2017-05-24 07:10
Here are attributes holding data for picklists:
`<aura:attribute name="years" type="DORLEXCtrl.wPickList[]"/>
    <aura:attribute name="months" type="DORLEXCtrl.wPickList[]"/>
    <aura:attribute name="countries" type="DORLEXCtrl.wPickList[]"/>
    <aura:attribute name="dealers" type="Dealer__c[]"/>
    <aura:attribute name="employees" type="Employee__c[]"/>
    <aura:attribute name="carriers" type="DORLEXCtrl.wPicklist[]"/>`

Somewhere are used wrappers, somewhere normal SF SObjects.
There are atributes for selected values:
`<aura:attribute name="selectedYear" type="String" default=""/>
    <aura:attribute name="selectedMonths" type="String[]" default="['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']"/>
    <aura:attribute name="selectedCountries" type="String[]" default=""/>
    <aura:attribute name="selectedDealers" type="String[]" default=""/>
    <aura:attribute name="selectedEmployees" type="String[]" default=""/>
    <aura:attribute name="selectedCarriers" type="String[]" default=""/>`

All have default value as empty string, only picklist for months have selected all months in advance. Data for years, months and countries is NOT populated from database as there are only few values so it is harcoded or generated on the fly on client side insdide LEX component controller.

This is example code how data is retrieved from database inside helper and how picklist options are generated. This works fine, problem is when user starts to type into input field to search for an item of picklist options, there is where everything halts to crawl. Some errors are thrown (mentioned in posts before) and browser starts to eat a lot of memory, like few GB's ob RAM for that tab and whole computer with 16GB of RAM get slow as hell. 
On sandbox I get filtered search results then in dropdown so component only throws few errors and it does it's job, but on production I get nothing. I have to force-quit browser and reopen page. This happen in Safar, Chrome and Firefox. 
`
getDealers: function (cmp, event) {
        cmp.set("v.loading", true);
        var action = cmp.get("c.getDealers");
        var selCountries = cmp.get("v.selectedCountries");

        action.setAbortable();

        action.setParams({
            "countries" : selCountries
        });

        action.setCallback(this, function (response) {
           var state = response.getState();

            if (cmp.isValid() && state === "SUCCESS")
            {
                // Get the search matches
                var dealers = response.getReturnValue();

                cmp.set("v.dealers", dealers);
                cmp.set("v.loading", false);

                //TODO: init dealers options - delete after strike components update/fix
                for(var index in dealers)
                {
                    if(index != "remove")
                    {
                        $A.createComponent("c:strike_option",{
                            "label": dealers[index].Name,
                            "value": dealers[index].Id
                        }, function (option, status, errMsg) {
                           if(status === "SUCCESS")
                           {
                               var picklist = cmp.find("dealerPick");
                               if(picklist)
                               {
                                   var body = picklist.get("v.body");
                                   body.push(option);
                                   picklist.set("v.body", body);
                               }
                           }
                           else if(status === "INCOMPLETE")
                           {
                               this.displayToast('Error', "Error creating option components for dealer picklist.", "error");
                           }
                           else if(status === "ERROR")
                           {
                               this.displayToast('Error', errMsg, "error");
                           }
                        });
                    }
                }
            }
            else if (state === "ERROR") // Handle any error by reporting it
            {
                var errors = response.getError();

                if (errors)
                {
                    if (errors[0] && errors[0].message)
                    {
                        this.displayToast('Error', errors[0].message, "error");
                    }
                }
                else
                {
                    this.displayToast('Error', 'Unknown error.', "error");
                }
            }
        });

        $A.enqueueAction(action);
    },
`

**Comment by trentchilders** [comment] 2017-05-24 15:33
Thank you for your detailed response. It's interesting to me that it works better in Sandbox than in Production. I'm not entirely sure what is happening but I have some things that maybe you can try. I'm interested to know how you are using your selected Values attributes. `strike_multiSelectPicklist` was designed so the value it returns is a semi-colon separated string of the values assigned to selected `strike_option` components.

So, let's use the example you have. You have a `strike_multSelectPicklist` with an aura:id of `dealerPick`. Let's say that for this component, you have set `v.body` as three `strike_option` components with values of "Dealer 1", "Dealer 2" and "Dealer 3". If "Dealer 1" and "Dealer 2" are selected, then on some event, maybe an onclick event, in your controller, you could execute this method:
```
handleClick: function(component,event,helper){
  var dealerPick = component.find('dealerPick');
  var dealerPickValue = dealerPick.get('v.value'); \\ returns "Dealer 1;Dealer2"
}
```
My concern is that you have somehow bound the value to those selected Value attributes which have their types set as Lists. It's possible something is getting lost in translation there. I actually don't think that those selected value attributes are strictly necessary, but if they are, you would need to convert the semi-colon separated value to lists in your controller and then set the attributes from there.

**Comment by trentchilders** [comment] 2017-05-25 15:23
Another thought: is there any real reason to keep the data for the picklists as attributes? If you are setting the body in the controller, that data is no longer useful in the context of the picklist. Of course you may need access to it for something else. I'm just trying to think of some ways to minimize the amount of data you have on a given page.

**Comment by matejp84** [comment] 2017-06-28 11:05
Ok after updating to 0.6.0 it seems components are working, but now I have a problem that this component is very slow due to large number of options. Is there an option that we could get some delay when user is typing for search or I can do anything to speed up things?

**Comment by kevinberonilla** [comment] 2017-06-28 14:07
Hi @matejp84, how many `strike_option` components do you currently have in your multi select picklist? I'd like to try reproducing your issues with the same amount of options.

**Comment by matejp84** [comment] 2017-06-29 08:15
One komponent has 305 items and other 1052. Logic here is that user first select items from first komponent (where there is less items - representing dealers), after he select dealers the other component (representing employees) will get only possible values - that is only employees that are employed at selected dealers. 

Users usually type in input field to search for items they wish to select, and if I for example search in employee component without filtering dealers first, component can take up to few seconds to show results. 
Now I know those components are not made for so much data, but for now I have no real idea how to solve this. And this is only data on sandbox where development and testing is going on, on production there will probably will more data as there is also component for selecting country, which filters dealers first. Also this numbers will grow on production because we are currently developing this for customer who will use this in multiple countries and more countries will be joined after some period of using our product, so in I think that employee count can rise over 5000 and dealers can get over 800. 

Now I was thinking to implement something like delay or minimum characters that would fire search function? Is this possible?

**Comment by mikeblazek** [comment] 2017-07-18 18:45
We will be adding support to do back end supplied data.  Meaning when you type in a we will fire an event that you can then pick up on and search through apex and return a filtered list.  Doing in DOM filtering at this level is just too much for the browser.  It should be coming in a future version.

**Closed** 2017-10-09 21:07 UTC
