### ISSUE TITLE
Datepicker Input field missing border

### ISSUE THREAD

**Issue by Appfrontier** [appiphony/Strike-Components#115] opened 2017-10-27 14:49 UTC
Seems winter 18 has broken this. The field does not display a border until a date is picked by the date picker. Pictures are in reverse order

<img width="302" alt="screen shot 2017-10-27 at 10 50 39 am" src="https://user-images.githubusercontent.com/16980522/32110102-b24412d0-bb04-11e7-9143-39f676c55bf2.png">
<img width="304" alt="screen shot 2017-10-27 at 10 50 26 am" src="https://user-images.githubusercontent.com/16980522/32110103-b252201e-bb04-11e7-9112-8a07e77da058.png">

**Comment by burhan7** [comment] 2017-10-27 15:54
Thanks @Appfrontier for logging this issue. We'll take a look at it.

**Comment by kevinberonilla** [comment] 2017-10-31 14:31
Duplicate of #97

**Closed** 2017-11-09 16:34 UTC
Labels: bug, duplicate, in testing
