### ISSUE TITLE
strike_lookup when used in strike_modal throws an exception on focus

### ISSUE THREAD

**Issue by Simran-Sohal** [appiphony/Strike-Components#57] opened 2017-08-04 00:54 UTC
If I use a strike_lookup in a strike_modal window, then as soon as I move my cursor to the lookup field I get the following error:
Uncaught Error in $A.getCallback() [Cannot convert undefined or null to object]

Screen shot is attached.
![screen shot 2017-08-04 at 10 52 12 am](https://user-images.githubusercontent.com/17467143/28949871-0a8f4296-7903-11e7-8b7e-eeed1cc30536.png)

Here the markup of the component where I am using both:
    <c:strike_modal aura:id="editModalWindow" title="Edit Support Information" 
                    primaryButtonLabel="Save" secondaryButtonLabel="Cancel">
        <aura:set attribute="body">
        <div class="slds-p-around_small">
            <lightning:textarea name="criticalInfo" variant="label-hidden"
                                placeholder="Enter support information"
                                value="{!v.criticalInfoEdit}"/>
            <c:strike_lookup label="Account"
                             object="Account"
                             searchField="Name"
                             placeholder="Select an option"
                             iconName="standard:account"
                             subtitleField="Industry"
                             order="Name"
                             limit="5"
                             loadingMessage="Loading..."
                             errorMessage="Invalid input"/>
        </div>
        </aura:set>
    </c:strike_modal>

**Comment by Simran-Sohal** [comment] 2017-08-23 05:04
Same error is coming when I add an anchor tag <a> to the modal window body

**Comment by trentchilders** [comment] 2017-08-23 21:07
Hi @Simran-Sohal. Thanks for logging this. First, try removing the `<aura:set>` tags completely from the markup. `<aura:set>` is not necessary for strike components. Then it appears that the issue is not with `<strike_lookup>` but with `lightning:textarea`. I will continue to explore why that is interfering with the modal, but for now, you can convert `lightning:textarea` to a standard `textarea`, which worked for me.

**Comment by trentchilders** [comment] 2017-08-23 21:30
Oh. I see. When using `lightning:textarea`, `label` is a required attribute. So add a label and remove `aura:set` and see if that fixes it.

**Comment by Simran-Sohal** [comment] 2017-08-24 00:07
Hi @trentchilders ... thanks for getting back to me. I will try the suggested solution and let you know.

**Comment by pauljrooney** [comment] 2017-08-25 00:12
I'm running into the same issue. In my case, the line that caused the issue was in `strike_modalHelper.js:42`:

```
if(!$A.util.isEmpty(el) && el.id == params.targetEl){
```

By commenting out the first part of the conditional things seemed to work as expected:

```
if(el.id == params.targetEl){
```

Somehow `el` is considered "empty" even though it has properties (including the id that's being checked in the remaining part of the conditional).

**Comment by Simran-Sohal** [comment] 2017-08-25 04:28
Hi @trentchilders ... still the error is there
Same error is coming when I add an anchor tag to the modal window body. As soon as I hover on the link created by anchor tagI get the error.

**Comment by pauljrooney** [comment] 2017-08-25 04:49
After fixing the issue with my line change above, I hit a second problem, this time on the lookup itself (instead of the modal component). There's an error in the function `handleFocusIndexChange` in `strike_lookupController.js:118`. In the case where the lookup is in a modal, `lookupMenu` can actually be null on the first focus event, so the fix is to check to ensure lookupMenu is not null before continuing in the function:

```
handleFocusIndexChange: function(component, event, helper) {
        var focusIndex = component.get('v.focusIndex');
        var lookupMenu = component.find('lookupMenu').getElement();

        if(lookupMenu != null) {
            var options = lookupMenu.getElementsByTagName('li');
            ...
        }
```

**Comment by trentchilders** [comment] 2017-08-28 20:22
I'm not getting this error on my end. Maybe this is browser related. Which browser are you using? @pauljrooney @Simran-Sohal

**Comment by pauljrooney** [comment] 2017-08-28 21:19
I’m using the newest version of Chrome.

**Comment by Simran-Sohal** [comment] 2017-08-29 04:19
I am using Chrome as well

**Comment by trentchilders** [comment] 2017-08-29 14:44
And are you both using the strik_modal version 0.9.0. That's the most recent release and the code that @pauljrooney has above does not match up with the current version. If you aren't using the most recent version, try upgrading and see if that fixes it.

**Comment by mrwel8** [comment] 2017-09-05 21:45
@trentchilders - I was able to replicate Paul & Simran's issues in version 0.9.0 as well as fix them with the lines below. 

FWIW - We were getting the error on a strike_modal that was opened from the "strike_evt_addNewRecord" event of a strike_lookup. The strike_lookup itself was not in a strike_modal at all. Seems like the issue for us was related to the contents of that strike_modal - Maybe because some of those contents did not have an aura:id set? Or maybe because that strike_modal was conditionally displayed using an aura:if?

strike_lookupController.js:122
```
var lookupMenu = component.find('lookupMenu').getElement();
if (lookupMenu != null) {
    ...
}
```
strike_modalHelper.js:48
```
var el = e.srcElement;
if (el != null) {
    ...
}
```

**Comment by pauljrooney** [comment] 2017-09-05 22:18
I believe I'm using 0.9.0, though it's slightly challenging to ensure I'm updated across the board using the strike cli.

In my case, the modal *contained* an aura:if, not sure if it's related.

**Closed** 2017-10-31 20:32 UTC
Labels: bug, in testing
